apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: groovy-visualization-prod

bases:
- ../../base

namespace: production

patchesStrategicMerge:
- deployment-patch.yaml

replicas:
- name: groovy-visualization
  count: 3

images:
- name: groovy-visualization
  newTag: production

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize
  environment: production