apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: groovy-visualization-staging

bases:
- ../../base

namespace: staging

patchesStrategicMerge:
- deployment-patch.yaml

replicas:
- name: groovy-visualization
  count: 1

images:
- name: groovy-visualization
  newTag: staging

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize
  environment: staging